const countries = [
  {code: 'US', name: 'United States'},
  {code: 'GB', name: 'United Kingdom'},
  {code: 'CA', name: 'Canada'},
  {code: 'AL', name: 'Albania'},
  {code: 'AU', name: 'Australia'},
  {code: 'BH', name: 'Bahrain'},
  {code: 'CN', name: 'China'},
  {code: 'CZ', name: 'Czech Republic'},
  {code: 'DK', name: 'Denmark'},
  {code: 'FR', name: 'France'},
  {code: 'GE', name: 'Georgia'},
  {code: 'DE', name: 'Germany'},
  {code: 'HK', name: 'Hong Kong'},
  {code: 'HU', name: 'Hungary'},
  {code: 'IN', name: 'India'},
  {code: 'ID', name: 'Indonesia'},
  {code: 'IR', name: 'Iran'},
  {code: 'IE', name: 'Ireland'},
  {code: 'IT', name: 'Italy'},
  {code: 'JP', name: 'Japan'},
  {code: 'KW', name: 'Kuwait'},
  {code: 'LT', name: 'Lithuania'},
  {code: 'LU', name: 'Luxembourg'},
  {code: 'NL', name: 'Netherlands'},
  {code: 'NZ', name: 'New Zealand'},
  {code: 'NO', name: 'Norway'},
  {code: 'OM', name: 'Oman'},
  {code: 'PH', name: 'Philippines'},
  {code: 'PL', name: 'Poland'},
  {code: 'PT', name: 'Portugal'},
  {code: 'QA', name: 'Qatar'},
  {code: 'RO', name: 'Romania'},
  {code: 'RU', name: 'Russia'},
  {code: 'SA', name: 'Saudi Arabia'},
  {code: 'KR', name: 'South Korea'},
  {code: 'ES', name: 'Spain'},
  {code: 'LK', name: 'Sri Lanka'},
  {code: 'SE', name: 'Sweden'},
  {code: 'CH', name: 'Switzerland'},
  {code: 'TH', name: 'Thailand'},
  {code: 'TR', name: 'Turkey'},
  {code: 'UA', name: 'Ukraine'},
  {code: 'AE', name: 'United Arab Emirates'},
  {code: 'UM', name: 'U.S. MO Islands'},
];

export default countries;
